### ISSUE TITLE
Support only netstandard2.1

### ISSUE THREAD

**Issue by secana** [secana/PeNet#113]
Drop support for older standards and framework. Remove preprocessor directives.

**Comment by ZonderP** [comment]
As far a I understand this document: https://docs.microsoft.com/en-us/dotnet/standard/net-standard
.NET Standard 2.1 isn't implemented by any .NET Framework (Neither 4.6.1 nor 4.7.x nor 4.8 - which will stay the final version of it before .NET 5)
Quote:
'3 .NET Framework won't support .NET Standard 2.1 or later versions. For more details, see the announcement of .NET Standard 2.1.'
.NET 5 GA is scheduled for Nov. 2020...
Wouldn't targeting just netstandard2.0 be good enough?

**Comment by fandrei** [comment]
@ZonderP @secana 
+1
targeting netstandard 2.1 instead of 2.0 makes NetPe incompatible with all the versions of .NET Framework

**Comment by secana** [comment]
Problem is that netstandard2.0 does not support `span` which I use heavily in the library 2.* version. Before the PeNet 2 version, I had many `#ifdef` all around the library which made it a pain to maintain. With the upcoming .NET 5 which unifies framework and core again, I'm not sure if it's worth the pain.

Do you have any current workflow where .NET Core cannot be used but only Framework?

**Comment by fandrei** [comment]
@secana I see. I'm rewriting the project to .NET Core, but it's quite big.

**Comment by yoshiask** [comment]
> Problem is that netstandard2.0 does not support `span` which I use heavily in the library 2.* version.

I'd like to point out that Microsoft has had a NuGet package that adds various `System.Memory` constructs to .NET Standard 2.0, including `Span<T>`: https://www.nuget.org/packages/System.Memory/

Is it possible to revisit this change and reintroduce support for .NET Standard 2.0?

**Comment by secana** [comment]
Hi @yoshiask that's a good idea. I'll look into it and see if I can release a .netstandard 2.0 version without too much work.

**Comment by IllidanS4** [comment]
It should be noted that .NET 5 is in no way a reunification of .NET Framework and .NET Core. It is a new and rebranded version of .NET Core.

**Comment by IllidanS4** [comment]
@secana I've tried downgrading the project to .NET Standard 2.0. To make it work, it needs the System.Memory package, but also IndexRange to polyfill the new types.

The remaining errors are missing functions in .NET that would take spans. One is in MMFile.cs, easily fixed with `fixed`. Others are in Encoding, should be fixable in the same way. Then there are Guid constructions, which would have to call the constructor with lots of parameters instead.

The rest are stream operations. Some of them oscillate between `stackalloc` and `new byte[]`, which can be neatly fixed with `#if`. Most of them are in StreamFile.cs, but I don't really understand its purpose - BinaryReader or BinaryWriter do the same thing, and I'd suppose them be in no worse state of optimization. Or you could simply call ReadByte or WriteByte and do the conversions yourself, which might actually be better since it will work consistently on big-endian platforms and Stream implementations will more commonly have these implemented instead of the newer Span overloads.

All in all, it should be possible without creating too much mess, and very appreciable, since I don't have means to use this now and the older version is not able to read from a stream.

**Comment by secana** [comment]
Hi @IllidanS4,

can you create a PR? Even if it is not 100% finished, it would be a good start.

**Comment by IllidanS4** [comment]
[Created.](https://github.com/secana/PeNet/pull/197)

**Comment by secana** [comment]
Version 2.7.0 with support for .NET Framework 4.8 it released

**Comment by IllidanS4** [comment]
@secana I am afraid this issue is not yet resolved. I was hoping to use PeNet in a .NET Standard 2.0-targeting library, but that is still not possible. Is there something that prevents changing the .NET Framework 4.8 version to .NET Standard 2.0?

**Comment by secana** [comment]
Added netstandard 2.0 support in v2.8.0
