### ISSUE TITLE
Digital Signature Friendly Name

### ISSUE THREAD

**Issue by heywannalaugh** [secana/PeNet#12]
Hi, I found a simple bug... Digital Signature Friendly Name is not working, it does not show the value.  Thank you!

**Comment by secana** [comment]
Hi, I looked into the issue. I don't parse the certificate by myself but use the .Net class X509Certificate2 for it. If the digital signature has no friendly name, an empty string gets returned. Do you have an example where an certificate has a friendly name but doesn't return it? Because that would be a bug in the Microsoft implementation of the X509Certificate2 class.

**Comment by heywannalaugh** [comment]
My bad, sorry, I was getting it confused with SubjectName ;).  Sorry about that!
