### ISSUE TITLE
Internal CLR Error Parsing Exe

### ISSUE THREAD

**Issue by gfs** [secana/PeNet#178]
## Background
I had a bug filed for Attack Surface Analyzer.  The user has identified (I've confirmed) that PE Net seems to choke on this binary.

See https://github.com/microsoft/AttackSurfaceAnalyzer/issues/560 for original report.

## PENet Trace
> Fatal error. Internal CLR error. (0x80131506)
at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UInt64)
at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UInt64)
at System.Span1[[System.Byte, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray() at PeNet.Header.Authenticode.ContentInfo..ctor(System.Span1)
at PeNet.Header.Authenticode.AuthenticodeInfo..ctor(PeNet.PeFile)
at PeNet.HeaderParser.Authenticode.AuthenticodeParser.ParseTarget()
at PeNet.PeFile.get_Authenticode()
at AttackSurfaceAnalyzer.Collectors.WindowsFileSystemUtils.GetSignatureStatus(System.String)

## File
[DRWUI.exe.zip](https://github.com/secana/PeNet/files/5598762/DRWUI.exe.zip)
File appears to be from [EaseUS Data Recovery Wizard](https://www.easeus.com).

**Comment by gfs** [comment]
This presents as a Segmentation Fault instead of a CLR error when run on Mac OS.

**Comment by gfs** [comment]
This repros on the latest version.

**Comment by secana** [comment]
Hi @gfs,

I had a look at the binary provided by you. I don't have a Mac and on Windows it works fine, so it seems to be an CLR issue. I released a possible workaround (version 2.5.1-alpha1), but I cannot verify it as I do not have access to a Mac.

Background:
When parsing the certificate information, the `BCertificate` member of the PE file is accessed with a `Span<byte>(from, to)`. Problem with this binary is that the range for the span is out of the range of the binary. This means that the certificate information is wrong and cannot be parsed. Instead an out of range exception is thrown and caught and `null` is returned for the certificate. That's at least how it works on Windows. For some reason, it seems that instead of throwing the out of range exception for `Span<byte>(from, to)`, the CRL crashes on macOS.

**Comment by gfs** [comment]
Thanks.

We were also seeing this with 2.4.2 on Windows and both versions on Mac.

Will try to confirm next week (considering holidays) if this file still crashes ASA on Windows with 2.5.0 of PE Net. 

I'll also try the alpha then.

**Comment by gfs** [comment]
Can confirm that 2.5.0 still exhibits failure on Windows but the Alpha fixes handling the sample file reported.

**Comment by secana** [comment]
Thx for the feedback. I released PeNet 2.5.1 which contains the fix.
