### ISSUE TITLE
How to modify import table after adding entry?

### ISSUE THREAD

**Issue by emersonjr** [secana/PeNet#207]
First of all congrats for the work @secana !

Following instructions I managed to add a new DLL to the import table of an exe file
But now I would like to edit its import table to have my added DLL to be the first import, originally there's already an entry that is the first one. How can I do that?

**Comment by secana** [comment]
Hi @emersonjr, that's a good question. I've never done it but I see two options. The first is to reorder all IMAGE_IMPORT_DESCRIPTOR structures in-memory and writing them back. I guess that is overkill and is likely error prone. Instead what you could try is to just change what the first and last IMAGE_IMPORT_DESCRIPTOR  points to and basically just switch their values.

I'll try to explain it a bit more in detail.

The import table is just a list of IMAGE_IMPORT_DESCRIPTOR structs. Each struct points to the DLL name and Address/Function name to import. If you add a new DLL and it is now the last IMAGE_IMPORT_DESCRIPTOR in the table, just let the the first table entry point to what ever your new import points to and the other way around. In that case you switch the first and last imported DLL. I'm not sure if something can break due to changing the order of imported DLLs.

I hope that helps!
