### ISSUE TITLE
ImageDelayImportDescriptor exception

### ISSUE THREAD

**Issue by heywannalaugh** [secana/PeNet#4]
Hi, there is an "index was outside the bounds of the array" exception in the ImageDelayImportDescriptor when opening certain files.

SupremoControl is a file that will help reproduce the issue.

http://www.supremocontrol.com/

Here is the download
http://www.supremocontrol.com/download.aspx?file=Supremo.exe&id_sw=7&ws=supremocontrol.com

Keep up the great work!!!

**Comment by secana** [comment]
Hi, thx very much for the bug report. As it seems the ImageDelayImportDescriptor of this executable is broken. The offset where it should be is greater than the buffer of the PE file, since the out of bound exception. I fixed the library and it shouldn't crash any more. Instead the values should be shown as null. Release 0.4.2 should fix the issue.

**Comment by heywannalaugh** [comment]
Very cool, thank you... wow, that was quick!  If I find anything else, I will let you know, but so far so good!
