### ISSUE TITLE
How to extract Debug Info

### ISSUE THREAD

**Issue by droyad** [secana/PeNet#52]
I've been digging through the source, but I can't figure out how to take an Address or Pointer and use it to read the section. Specifically I am looking for the hash/signature and age in the `ImageDebugDirectory` data. Any pointers would be appreciated.

**Comment by secana** [comment]
Hi @droyad, I'm not quite sure if I understand what data you want to get out of the PE file. Could you elaborate a bit more what you want?

**Comment by secana** [comment]
Hi @droyad, thx for the explanation. Unfortunatly there is currently no way to get the "RSDS, {96F231BD-9207-421C-9EF5-28D2F4DF0B81}, 1, D:\ExternalRepos\PeNet\src\PEditor\obj\Release\PEditor.pdb" information from PeNet.

Unfortunately, I'm very short on time a.t.m, so if I have to do it, it will take a few days. If you hack something together, I would be super happy about a PR, because especially the debug file path is really interesting for malware analysis. If you could extract the information, that would be great.

**Comment by droyad** [comment]
No worries, I'll see what I can scratch together later this week.
