### ISSUE TITLE
TLS Callback

### ISSUE THREAD

**Issue by heywannalaugh** [secana/PeNet#6]
Hi, I am not sure that the TLS Callbacks are working correctly.  Files that use TLS callbacks are somewhat rare, so I searched for a sample and analyzed it with another PE utility, and it showed the TLS callbacks, but for some reason, they are not showing in PeNet.

For example if you download and compile this code: 

https://docs.google.com/uc?id=0ByDwYV_JGWRNNTZkMWUzMjYtNDljOS00YmNjLWFlZDItMWRjYTI0YmY5OWVk&export=download&hl=en

Here is the website where I got the above link: http://waleedassar.blogspot.com/2010/10/quick-look-at-tls-callbacks.html

One quick question... what is purpose of the AhoCorasick class?  It looks really cool, but I do not see anything that calls it.  Just curious.  Thank you!

**Comment by secana** [comment]
Hi again. You are right, I took the TLS callback address an RVA instead of an VA which leads to a wrong address computation. I fixed it and uploaded a new NuGet package (0.4.3). Thx a lot for reporting the issue.

The purpose of AhoCorasick is an popular algorithm for pattern matching. It is used to detect byte opr string pattern in a PE file. The idea is to find specific pattern which identify malware or a packer. For more information about the algorithm see: https://en.wikipedia.org/wiki/Aho–Corasick_algorithm
If you want to try it with the PeNet library have a look at: https://github.com/secana/PeNet/wiki/Pattern-Matching

Regards,
 secana

**Comment by heywannalaugh** [comment]
Very cool, thank you!

Cool, I will check out the AhoCorasick algorithm, it looks very interesting.

BTW, besides looking at the manifest in the resources directory, is there any other way to determine if the PE file is set to run as administrator?  Thank you!

**Comment by secana** [comment]
I've to thank you for reporting bugs ;)
The manifest in the resource directory is the only way I know, too. If you ever lean of another way, let me know.

**Comment by heywannalaugh** [comment]
Sure, and thank you for writing such cool stuff!

Yeah, if I find another way to find the run as admin, I will let you know.

BTW, I found a file that reproduces a bug... I might find a couple more over the next few days because I am going to be testing A LOT of files.  

The file is called "dosx.exe", and it is in the system32 directory of Windows XP.

Do you want me to email the file to you?  If so, what is your email address?

Thanks again!
