### ISSUE TITLE
A couple small exceptions

### ISSUE THREAD

**Issue by heywannalaugh** [secana/PeNet#7]
Hi,

Here are some files that reproduce a few minor bugs, they are all clean Windows files.  

I also have some malware files that have similar issues, but I think fixing these minor bugs will fix the exceptions for the malware files, if not, I will let you know.

You can download the files here: 
www.desktopfolders.com/FilesWithErrors.zip

Thank you!

**Comment by secana** [comment]
Hi heywannalaugh,
sorry for the late answer. I was on vacation without any internet. I will have a look at the samples as soon as I've time. Again, thank you very much for your bug hunting :)

Kind regards,
 secana

**Comment by heywannalaugh** [comment]
Very cool, thank you!  Once these small issue are fixed, I will test it with tons of malware samples and let you know if there are any other issues... I do think there will be anymore though... your code is super solid.

**Comment by heywannalaugh** [comment]
Hi, I just noticed something, I am not sure if it is supposed to be this way or not, but I wanted to at least mention it.  The PEEditor imphash does not match the VirusTotal imphash...

Here is a link, just click on Additional Information, and you will see their imphash.

https://virustotal.com/en/file/db63a0b433e72f65b6f7696b554b47c44b6dfca5937e3f2a349b4fb042c6bc19/analysis/

I was not sure if imphashes used an industry standard or not, but I wanted to just mention this, thank you!

**Comment by secana** [comment]
I had a look at the exe which crashes the PEditor. It is not a valid PE file and thus cannot be parsed. The PEditor catches the error now. 

The files in the "These all have the same issue also" are also not valid PE files. Actually their are nothing at all, since their file size is zero ;)

The files in the "These all have the same issue" seems to be a bit more complicated. They are not valid PE files but have at least a valid DOS header. The rest seems to be garbage. The exe files cannot be parsed at all, but the dll seems to work at least to some point. If you check in the file header for the "Machine" flag it will identify an unknown type which should no be. May I ask where these samples are from? Could it be some COM/.Net format?

I've published an updated version with a little bit better crash handling.

**Comment by heywannalaugh** [comment]
Hi, they were just all files from Microsoft Windows... I think most of them were from XP.

Cool, I will try the updated version with a lot of malware and see how it goes, thank you!

Do you have any thoughts of the imphash?  Is it a standard hash like SHA256 is?

**Comment by secana** [comment]
Hi. Regarding the ImpHash. It's not a standard hash like SHA256. A company called "Mandiant" is some kind of the inventor of the hash. You go over all imports of a PE file and concatenate library name + function name and than make an MD5 over the string. 
Nonetheless my implementation should have the same results as the "official" python implementation by Mandiant. I checked the python code again and found an error in my code. In the rare case that a library has two extension (like wspool.drv.dll) I cut of "drv.dll" but correct was to only cut of the ".dll" part. I fixed it an published version 0.4.5 which now yields the same results as you see on VirusTotal.
Thank you very much for reporting this bug. Wrong ImpHash could lead to a lot of problems ;)

**Comment by heywannalaugh** [comment]
Very cool, thank you!  BTW, I hope you do think I am being a pain ;).  I doubt I find anymore bugs, your code is very solid!  

I have a quick question though, have you thought about adding "Entropy" to the sections and for the entire file?  Also, have you thought about adding strings as well?

**Comment by secana** [comment]
I added a project to the GitHub page, and added your ideas. I'll implement the stuff when I've a bit spare time. If you find any more bugs notify me. It's good to get some feedback and to improve the project :)
