### ISSUE TITLE
Issues that freeze

### ISSUE THREAD

**Issue by heywannalaugh** [secana/PeNet#8]
Hi.

I found some malware that freeze your project.  It looks like it is an easy fix, and some of these are the same issue, but I figured I would send all of them to you just in case.

This is real malware, so I zipped the files with the password: infected

You can download the malware files from here:

www.desktopfolders.com/Malware.zip

Thank you!

**Comment by secana** [comment]
Hi,
I fixed the issue in 0.4.6. The problem was an invalid relocation directory. The parser hung up because it tried to parse billions of relocations, which is obviously non-sense. I added an sanity check for that case and now it should work.

Thank you again for bug hunting. Thx to you, PeNet will be the most stable PE header parser of all time :)
